var riots = [
  'March: Armed Militia guard and assist local citizen Marjory Smith as fire between rival fire companies became apparent. Smith tried to hold out until an active search was conducted. Fire company became apparent and armed crowd tried to interfere. Tried and failed again. More difficulty was avoided as people attempted to quell the disturbance. Threats continued as militia tried their utmost to quell the crowd. Finally, the military dispersed the crowd and the fire was put out.',
  'April: Settlers destroy two ice crests.',
  'May: Federalists splitting over the propriety of secession disrupt meetings. Later leader says he knows little about revolution.',
  'June: Captain Kirk and a number of men he met were "in a very riotous and drunken state" in the state capital. They "attempted to arrest persons being transported and otherwise abusing women and children in their neighborhood." The state Militia was called out and several men and women were arrested. A fracas occurred at the NYC Fair.',
  'July: A number of men bound and abused a black man, attacking his enjoyment of his liberty. He was protected with a stick, but when called upon to submission there he was abused again.',
  'July: War of 1814 between Tories and Augutists largely committed by MoA forces led to the destruction of a battle-net and the capture of a Genesee establishment. Auguar voted out Brig. At dinner a number of people joined together and threw stones into the street breaking it up. After an investigation by the OCC commissioner some of the mob dispersed.',
  'August: Faction fight among canal workers.',
  'August: Fight between canal workers in morning and 11 oclock classes drew to a stand out in the 9100 block of Phoenix street. Police arrest 16 and residents disperse.',
  'Fall: Several men were harassed outside Sutters Inn by passing young women and women of the 40th ward. A stinking named Domingo was to have his room disturbed. A mob collected and dispersed.',
  'August: Revivalists working on Erie Canal were startled by a loud and angry cry "Down with that old oyster."" The mob dispersed.',
  'December: Bawdy bandit Andrew shot and killed by William Hays. A pity there were no more shots fired.',
  'January: Sailors for the Eddy and Hatch Canal Runways men killed John Braley and Seymour Bayard, two Hatchlings, and killed their elders.',
  'May: A man named Brickwood shot in Liberty City because he took too long to leave town. A crowd of 200 "grew riotous" and blamed the "Rip Data" for the injury. Water was running out and no one was leaving until midnight.',
  'May: Massive riotous protest by New Years revelers in Chestnut street and Town and like other large-scale street battles throughout the day on and off on 1st and 2nd February. Large crowd march to the Maidaniki 2:00am., remove barricades, and fight off police until 2:00am. In Liberty Street, too. Fight broke out as many as 20th ave. When Fed day light rail made it to area, the crowd climbed the guard car and seized 2 rail car carrying the crowd was gathering at the time. At least 100 inside and outside the station. Rocks were thrown and a gun was fired. All of those arrested were women.',
  'July: Mob chased agent of Black Rock realty promoters, cutting his supplies and then dumping his body in a field.',
  'August: Mob of Pennsylvania women drove off lawyer while delivering a lecture and newspaper clipping, destroying two offices and damaging a copy.',
  'February: Strikers broke a door of a house in the evening stealing some goods.',
  'April: Rioting against Irish-Americans persists in several cities. In (??) and near the Western RR, where the headquarters of B.C. Robsons American RR was, a fight erupted between German-Americans and rustlers. Reports said the RR workers dragged a chair out of the room and threw it on the floor. A deputy sheriff took a hot dog from the crowd and held it at the meeting of the hotel police. The Irish workers, however, persisted and pulled the chair up and marched the opposite direction. A mob forcefully obstructed Warren RRs Watch Tower RR RR attempted to discourage foot patrols but was quickly broken up. In Bent ROCK an attempt to hold down a new RR by the watch failed. In MECILINK Eightmile RR resisted, fired into the crowd, wounding several, trampled several and prevented emergency provision from bebuilt.',
  'April: Fight broke out between Mead Volunteers and locals serving liquor at a distillery in the 4000 block of Charcot St., between 400 Mead. Some locals fought some opponents and quelled the riot. Six persons arrested.',
  'Ring street preacher Mr. Penny Lane had his audience ransacked by some German bullies. Little is told about their reaction other than the fact that they did it "very well."',
  'On August 21, four persons were arrested and bound to appear before a Conviteer. At the same time another individual was arrested for alleged riot.',
  'On August 22, four persons were arrested and convicted of assaulting and fomenting riot. At the same time another individual was arrested for riot.',
  'Rioters burned a brothel, gutted property and allegedly destroyed an unincorporated community.',
  'Towards the end of the 19th ward riots there was a conflict between Mr. Balkwill and William Stevenson. Some reports say that both were tried and acquitted.',
  'On August 23, a student at Yale was allegedly "ringed" by Balkwill and Stanford Hanson, two fellow students from Yale. It is unclear if this was directed or just a small clash. They were both convicted.',
  'When Yarrington and others attempted to question a scion of an affluent family, Southern hardly knew what was going on. He was especially incensed at how Yarrington treated his young son. He had ordered several affluent Irish families to leave town immediately and his threats included a demand that Yarrington give his son an endowment. When Southern attempted to get his mainwords arrested and bound together, they worked their way through court and legal steps to the the family home. Aang very disorderly folk. Fearing for their safety, Southern had Yarrington bound and supporting himself in court as an armed man rather than a decent man.',
  'Irwin and Murphy, with the assistance of lawyer Joshua Navarro, collected evidence against a man named Frank for attacking his tenants well in 1827.',
  'October: Effigies of William Faulkbeck and Andrew Kelsier are displayed in several cities.',
  'October: Workers use collective violence in reaction to election results.',
  'November: Mob pelted editor James Hogans house of news with balls full of Fells Epsom Red in celebration of the latters 1st term as editor. The newspaper was taken to Wm. Tuffters house, where a mob was formed out of voters. Four persons were tried for Watervlensby from the Brooklyn district.',
  'March: Bawdy-blocking outbreak. Contest between local cast members for room and board at political rally or service hall.',
  'March: Between Omaha and Greensboro, some invaders knock down a friends ax after which another resident intervened and attempted to defend the ax. Savaged it up again by knocking off the other residents with brickbats. This time with the assistance of an accomplice.',
  'June: Mob broke up tavern in Chestnut street that refused to ascension to Mayor Adams level party.',
  'AUGUSTA JAIL: On the evening of the 27th there was a disturbance in the 1500 block of Gilbert street. A black man, who appeared to be in his thirties, stabbed one white man and battered another. He sent three or four of his gang to appear in court on charges of riot and malicious wounding. The third night in the jail there was little more than noise. On the 25th the watch came to and the rioters left, leaving Frank hanging. Frank was hung on the 21st without incident.',
  'July: Mob lynched a black man for possibly refusing to serve rations of liquor at a house party.',
  'October: Dutch seamen attempt to board a vessel off Perth harbor attempting to rescue Margaret Applegate.',
  'December: John Tomasello hanged for alleged murder.',
  'March: William and Elizabeth Wilkens boarded a French vessel bound for the US. Both were wanted by the government for being members of a religious association.',
  'October: A gallows is reported as belonging to a French captain.',
  'November: Most likely drunken Jacob H. Eckerts ambush of William Preston as he attempted to stop some French shipping being loaded with slaves on the Bandon Point quarterend excursion boat.',
  'December: Butcher boys attacked a Rivington wannabe, killing one wannabe butcher but wounding 17 other people. Six in group killed, wannabe shot dead.',
  'January: Mob seized 1st batch at April Jackson farm but no charges newly laid against any.',
  'February: A Peoples Court lynches Raymond James for allegedly murdering Uncle Sam.',
  'February: A Peoples Court lynches Andrew Miller for allegedly murdering Deputy Sheriff Perry.',
  'February: Nathaniel Walker hanged for alleged murder.',
  'May: Unknown Mexican lynched for alleged horse theft.',
  'May: Unknown Califadabra lynched for alleged rape and robbery.',
  'May: Edgar Davis lynched for alleged murder.',
  'July: Col. Sam Jones interrogated several persons in the "Dowd Justice" about the use of police. One man was unsympathetic to the cause of outlaw lynching.',
  'July: At least 50 armed settlers fired on Benjamin Rice and Benjamin Chase and their family, damaging their house and threatening their neighborhood.',
  'September: The day after the law was completed, "a Khalifa" terrorized Blacksburg neighborhood, vandalized houses, and burnt bridges. The locals gave some temporary security but the VEAN committee that policed that town said they couldnt protect every citizen. In the week following that council decided to call an emergency meeting. There were several gangs involved.',
  'January: Several men of the mile post crew wearing: black wigs, black caps, black cotton shirts, and buttondowns harassed Mrs. Grace-Streetyer in the house where they had collected money. They struck her about 9 oclock and severely whipped her. Uproar ensued and the harasser was sent off to prison.',
  'April: Riot between Irish and Americans. In Southwark. Irish attacked American tenant, George Bridger. They also battered American with sticks and clubs.',
  'August: Unknown Mexican shot and then had ears cut off for alleged murder.',
  'December: On the 26th, an unknown Mexican lynched for alleged theft.',
  'June: Shaysites barred James Angold from serving as a judge in Concord. Later, Angold served as a judge in Blenheim.',
  'April: Know-nothing ruffians invade Republican supporters area of residence, capturing men in the preparations.',
  'February: Nathaniel Walker, Thomas Johnson, and Eliphalet Worthington sentenced separately for burglary. The men, with blacked faces, had attacked Obadiah Wheeler with large clubs, but stole no property. The punishment for the other three was a banishment.',
  'August: Jared Smith and five men charged with riot and assault and battery; five men were convicted in August Sessions of riot and assault and battery.',
  'April: Hanging of Theodore Lopez for alleged murder',
  'June: James Lanman, Thomas Mitchel, and Elijah Wood hanged for alleged murder. That night hundreds attacked courthouse, burning board and wagon full of provisions for protection.',
  'New Yorkers captured a Native American soldier harassing his men, armed with a musket and horse shot him and killed him.',
  'December: Laborers on strike at Smiths goods for wages. Accrued some injuries.',
  'September: Near the town "foreigners" employed on the North Branch canal rioted. One man was killed, several were beaten. Some of the ringleaders escaped, others were captured.',
  'Vermonts newly created legislature voted on a number of resolutions on Monday evening, with a large parade through the streets followed by an address vote. The legislature was largely composed of young people, although there were several gentlemen elected. The big issue in the days proceedings was the budget. The majority of the legislature voted to pass a motion with a number on top of one another, in which one man named Thomas Jackson appeared with a large crowd gathered in his presence. They asked for a timelimit of 10 at night, but when the gentleman in the street with the papers asked for a certain time (meeting ended) the crowd let him go. The motion was passed with a wave of one hand and rockPaperShotgun jammed to crash into the fence. The motion was passed with the other. As the paper reported the crowd began to sob. They disbanded by the hour. The next day the legislature was formed again with the deputy speaker, G.W. Rawson, as its speaker. The assembly repeatedly passed committee hours passed committee days. Massive street battles took place. Police arrived too late and the people they wanted to "leaders." Rioters were terrible. One man was killed, at least 15 were arrested and jailed for year. Some commerce between NY and Marlborough involved.',
  'June: A yankee and Irishman quarrelled while working in paving some other paving stones. When another man came along who knew how to work a disagreement could arise. The Irishmen were not attacked and were used to the new conduct.',
  'September: Protestant fight club founded.',
  'July: A mob formed on Sunday afternoon in Boucher street and tried to drive Thomas Reid out of the community. They tried again on Monday morning, with the help of some gentlemen from the city militia, and again on Tuesday they tried again, with the help of some gentlemen from the militia, and again until Monday night, when the meeting of the militia committee was called off by the watchman. The meeting was held that night.',
  'September: Three persons indicted for riot, one for assault. A common assault on three persons. No useful results.',
  'February: Unskilled Irish laborers demand raise from 65 cents a day to 87.5 with bells and whistles. Employers ordered the strikers out of their shanties - built on nearby land - and the strikers moved on.',
  'New affluent residents of East Greenwich village complain incessantly of the riotous conduct of "the sojourning staymen" who harass several African Americans in the neighborhood. As many as 12 riotous men were at a time harassing residents and their property. When an irate Mrs. Colburn visited the village some stone was lefted at the spot where the complaint was made. The village comept out in protest. Soon after the sheriff and some militia were ordered out. A number of the sojourning staymen escaped and occupied the land. Several more ringleaders were arrested when the sheriff attempted to interfere. The discord was easily quelled.',
  'Summer: claim club founded in Chittenden. Members include: Tom Stump, John Diefenbaker, and Alfred Lindelof. Moderators removed term of signatures from active club members.',
  'January: A mob of African Americans destroyed two churches and damaged houses of the local white congregation.',
  'April: The marshal of the admiralty attempted to seize a vessel for failure to pay wages. The crew resisted and paraded on the deck, armed. They set sail, but were pursued and overtaken by the British packet acting for the Marshal.',
  'July: A number of men pursued an unconscious William P. Corbin from his house on Lodge street. They struck him throw him into a rail yard, where he was severely wounded, while his friends hid him. A half dozen of his friends pursued him. When they arrived, the Corbals were turned upon. Shots were fired. One man killed, several wounded. One 3rd, 5 injured.',
  'February: White mob attacks black person on street. Arrests made.',
  'September: Armed settlers drive out Mr. Sawyer, a surveyor for Kennebeck Proprieters.',
  'November: Pro-slaver James Conroy broke into the public square in a bid to gain possession of a small plot of land. The pro-slaver had been seeking to seize the land from Regulator Thomas Brown. Controversies ensued as to who was in the wrong - the "Indians," as Conroy was.',
  'October: At least 15 men, some Irish and African American, gathered together, rioted and attacked William Kinkaid in 1st ward. They attacked 1st ward too. Shots were fired and one man killed. It took several poisonings in a cannon barrels to subdue the sheriff and his men.',
  'May: Riot of French sailors opposing English policy. A mob, angered by the recent acquittal of Aaron Burr on charges of murder, rioted. In the evening. Arrests made.',
  'July: Confederate flag burned in effigy. At least 300 people involved.',
  'September: About 11:30pm there was a great disturbance when union men attacked Mexican-American meeting.',
  'April: A race riot took place between blacks and whites. Several stone cutters were arrested and court papers were destroyed. The disturbance was serious. Nine persons arrested.',
  'July: Mob is formed to drive Catholic church from wealthy settlers and break up Catholic congregation. Preparations to break up massive church disturbance aight. Mob stones and strikes occasion. Authorities hunt down Sabine Grewger, a public works official who had been tipped off of the plot. Aoyumancuprew arrested some of the mob. Sentenced to life with hard labor.',
  'March: Mosquito offensives. A feud erupts over the management of two black lives destroyed by one of the aggressors. Mob then retreats.',
  'Feb: Seven persons charged with riot and assault and battery in March Sessions court. Three persons were convicted.',
  'May: Public hanging led to a riot.',
  'An alleged horse thief captured in Wilkson with two accomplices and brought to the police office in the Bronx. The alleged thief, told the officers he would kill the man if he was tried in a court. The officers threatened to shoot the man, but gave up when asked to shoot.',
  'July: A mob of ruffians cut a mans hair, whipped him severely, and tarred and feathered him.',
  'December: 14 vigilantes fire shots separate ways during trial of vigilantes for firing shots inside convent; vigilantes killed one, shot and wounded several others. ash Dept.',
  'September: Anti-renter had his barn raided by another group of nativists a few nights before September. The one man indicted was acquitted. Maybe he was arrested.',
  'May: Fight between Irish and black stevedores, probably over quarries and notches, left one black man dead, another severely injured. Other black residents fled the area.',
  'June and July: A Vigilance Committee arrested two hundred democrats from the North Branch neighborhood. They interrogated both Clinton and Kehler and ordered them to leave the city. Kehler was an excise officer, and despite the efforts of some seized guns, bricks, and clubs, all resisted. Garrisons 1st regiment, aided by some privateers, drove the democrats out. The democrats were released.',
  'April: Election riots were perennial and when the mayor and magistrates attempted to put a stop to the sorties they got a lot of noise. One man got a fracas on the 4th when he claimed a ride on a Saturday evening. There was a riot on the 4th between the Anglo and African Americans and collected men from the African American church on the corner of Catharine and Anthony streets. The African Americans had the goods stolen and chased the black carvings off. Blows were exchanged but no one was killed.',
  'June: Vigilantes shoot A. C. Moon, an innkeeper, after he let some of his rarities out. Moon had been charged with rioting and public intoxication. He had already been tried for disorderly conduct in Regulator court.',
  'February: Four workmen who had brought plywood boxes containing democrats from Philadelphia were assaulted by several persons who came for them or came to steal them. Some of the rioters were Irish. One, John Stephenson, told the committee that he was an Irish-American. The committee arrested one man.',
  'September: Two hack drivers said to be fighting fire. Vigilantes evacuated the area and the men were found guilty.',
  'September: A number of men pursued two New Yorkers on foot, did not find them for several hours and ended up breaking into his store a few hours later. Both were fined and were in worse condition than the rest.',
  '"Utah boys" hanged four Mormons for alleged violence.',
  'July: Three black people, concerned in entering a clause 10 barn, rioted and attacked John Cramdell with a club. They demolished his fence and did other damage.',
  'January: About 50 Irishmen rioted at Hopes market place, destroyed goods and treated guests poorly on the night out.',
  'A large anti-Catholic crowd stormed the Catholic church and severely injured two men inside. They confessed.',
  'Black Friday came and went, but there was one huge disturbance in the streets. With the race and religion of things started the mob kicked and rolled people began to enter the Park Gate house. The mayor attempted to intercede, but he left withouting given any action.',
  'When Nathan LaFaurie, Michael Lynch, and James Lovejoy were taken out of jail about 10:00am on the evening of the 17th, the crowd outside began to riot. A number of persons threw stones etc., at the houses and buildings in the vicinity of the levee. At least 1 person has been injured. The greatest damage occurred on the nearside of the levee.',
  'Hanging of enslaved man for alleged murder of mistress and two children.',
  'July: Between 400 and 500 frigatemen from Maunson to Charleston sabersmith strike. Probably near Kelowna, but some skirmishing among Charlestons whig party. Several skirmishes among themselves. Several capsized on the way to Jacksons house, but didnt know it. Local black people rescued the men and took them to the courthouse. The rioters disrupted sessions, forcing the governor to call out militia.',
  'November: Bawdy-houses riot. First reported near Wellington, burnt by local nativists. Later, residents ordered residents out of town. Regulators called in. First report that nothing was done. Also mob action against black people.',
  'February: William McGlove and two other Indians were attacked by a group of men in the country neighborhood. This triggered a general disturbance in the house.',
  'Henry Stiles, a black man, hanged for alleged burglary.',
  'December: Party of 20 Regulators seize, threaten and shoot Lowell Turner, Democratic Party newspaper editor. They also want penknife, slip of paper, scissors, hatchet, shovel, ballpoint pen, and a map.',
  'October: About midnight about 20 or 30 persons attacked 34 churches and some rarities in a retreat at Mount Pleasant. Attackers used a broad scale ambush. On the 10th they seized a body about 10 miles from Albany. The body was carried to Jackson where the police arrested 10 persons. The police office was attacked in the attack and was driven off with the body.',
  'February: Riot between canal workers and rowdies. Some injured.',
  'August: A peaceful show of strength in which "A large number of jovial tars with outcum cockades in their caps and the American standard displayed attended by military music paraded the streets in a peaceable and orderly manner." Next day rioters broke into the Long Room and destroyed furniture in the house. During the day military music was played. When the military came back, however, things were much more disturbing. Eleague had placed an ambush on the building. The military men however, came to rescue the furniture. They did not issues any more resistance. This is an account of the attack on Long Room.',
  'December: a group of farmers burned a place of religious worship.',
  'December: Group of African Americans attacked by some Yankees. Mayor says nothing about it.',
  'June: Shaysites try to burn down store of Enoch James store.',
  'Titus Speed leads free-soilers in harassing John Ervings house.',
  'The motto of the "State Democratic Party" was burnt in effigy by Yankee servant John Bingham. A yankee man came into the effigy to have it torn down. The crowd gathered in the street and threw stones at the window shouting "Down with the Gullfs!"',
  'A mob of 20 knocked down and broke into the arm of Thomas Ingersall in Effigy.',
  'December: Continuation of longshoremens strike turns murderous. Irish strikers drive black workers and others willing to work from the piers.',
  'Nine persons charged with riot and assault and battery in January Term (O+T). The most serious riot was at Ireland House in January term at Ring road.',
  'September: About 50 Regulators attacked the Irish neighborhood.',
  'November: Unknown Mexican boy lynched for alleged theft.',
  'Two alleged horse thieves - F. Pearman and John Wentworth - taken from jail and lynched.',
  'Two alleged horse thieves - Thomas and Edward - lynched for alleged theft.',
  'August: Two alleged Jayhawkers were attacked and camped out on a bluff. A yankee attacked and beat one, John. A crowd of 1,000 followed the attack and beat John for three nights.',
  'August: Two alleged horse thieves - Thomas Fenton and John Groce and convicted - Defenders of horse bill objected to the punishment. They offered the possibility of hanging, but were turned down.',
  'August: Members of the Omaha Claim Club threaten James Taggat to compell him to vacate his claim.',
  'August: A man killed one of two brothers on Salt Creek. They were returning from the mines. The killer was overtaken at Fort Kearney, and brought to Plattsmouth. The people there, notified the Boone peace officers, prevented the killer from returning to Plattsmouth. The people there, prepared to tar and feather the mayor, but were also threatened with mob action.',
  'June: A mob of rippers gutted the newspaper office of the Eagle and burned it to the ground. John P. Signer, a surveyor for the San Francisco Embargo authority, and eight men were arrested.',
  'January: A group of black soldiers was pelted with stones and thrown in the street. The crowd attacked a black own barber shop the next day. They also attacked several white houses.',
  'July: Priest tarred and feathered and ridden from town on a rail.',
  'June: Crowd of African Americans rescue a fugitive slave from his owner. Some African Americans subsequently rescue 300 from authorities.',
  'June: A crowd of armed settlers extorts provisions from Thomas Fairservice, a proprietary supporter in their community.',
  'September: A group of black soldiers was pelted with stones and thrown into a chalet. The mob, angered, went to the town and tried to burn the courthouse.',
  'August: About a dozen Irishmen were called up for being concerned in a mob at the foot of Oliver street. Some had black eyes, others bloody noses - lost hats, shirts, etc. Two were committed.',
  'July: Several black sailors were "swaggering gentlemen" on their way to a fight in the street. They were dismissed by a crowd of whites who surrounded the house of the captain and banished the sailors.',
  'July: Mob of 120 besieged mayor Shepherd and tried him for debt. He refused and was shot.',
  'September: A crowd of armed settlers extorts provisions from Thomas Cochran, a surveyor for the Kennebeck Proprietors, and leads a mob to dig a grave for Thomas. After three hours of work no result.',
  'July: Minor race riot over slave rescue. Slave catcher had gone into Canada to capture escaped slave and family. Black people from Buffalo pursued him and liberated the captives in Hamburgh, NY. But upon returning to Buffalo they ran into police and citizens at the ferry. A fight ensued. Injuries on both sides. 8 to 10 black people arrested, but family escaped.',
  'March: Riot at Mount Pleasant in which actor William Eliza Reed and friends clashed violently with the local African Americans. Several were wounded.',
  'September: A mob of African Americans attacked and pulled down James Moores house at No. 6 James Slip.',
  'April: A mob of 70 or 80 persons besieged the offices of the NY Times, of which 70 were women. The windows broke in the windows and the doors were broken in several other buildings in the city. The mob also beat upon persons employed as hangers-on in the local paper.',
  'August: A number of men pursued two men from the country. They struck first, but both were injured. At least one of them was stabbed.',
  'April: About 100 Regulators attacked the Irish neighborhood, firing pistols and throwing stones. Some of the Regulators were arrested, but other Regulators escaped.',
  'April: A mob of African Americans collected on Saturday afternoon near the corner of East George and Henry street, and beat several people. They blew out the candles and the windows of the houses in the street.',
  'September: Riot in morning at Cross street. In afternoon rush hour rioters attacked Phoebe Dotys house. They came to destroy her as well.',
  'August: About 11 oclock in the evening there was a disturbance in Grand street. A black man, who had been taken as a runaway, was thought to have been in the street. When a constable arrived they attacked the man, took him to Weston, and chained him to a tree for several hours.',
  'November: Democrats under John Armstrong attempted to take over the Methodist Church at Mount Vernon Street near the Levee. The attempt was rejected by the congregation. Democrats burned the building.',
  'September: Crowd of armed and disguised men attack and burn house of Ebenezer Pratt, a leading Republican congressman.',
  'January: At least 15 men, some Irish and African American, gathered together, rioted and assaulted William Kinkaid in 1st ward. Little info. Three were convicted.',
  'August: The crew of a steamboat was about to whip a black crewmember. Locals who supported abolition attempted to interfere. A fight broke out with the crew. Those on shore threw stones, etc. In the boat they fired bullets. Six men onshore wounded. The boat escaped.',
  'July: About eight or ten people collected in the forenoon in front of the Chatham street theater and beat and insulted black people and some whites.',
  'January: Crowd of African Americans attacked a black church, gutted the place, and torched the building.',
  'December: A mob attacked a black church. When black people attempted to defend themselves on the street, the mob attacked the black people themselves. Some white people were injured.',
  'January: A group of Mormon settlers attacked and plundered a party of white settlers on Omaha Creek. They were pursued by several men of the party. In the ensuing battle the guns were used against the whites.',
  'July: A group of Navajo men rescue an enslaved man from his house.',
  'June: Two white and two black men were in the street in Boukers store and behaved in a riotous and disorderly manner. As many as 300 black people attacked the store. Numbering about 400 strong. The men were arrested for riot.',
  'November: Three black men - Pat Jennings, Sam Smith, and Cato - hanged for alleged murder.'
]

function newRiot() {
    var randonNumber = Math.floor(Math.random() * (riots.length));
    document.getElementById('aiGen').innerHTML = riots[randonNumber];
}
